# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "zayass/swift-android-base"


  if ENV.has_key? 'VAGRANT_SHARED_FOLDER'
    puts "Host folder: #{ENV['VAGRANT_SHARED_FOLDER']} will be mounted to guest: ~/shared"
    config.vm.synced_folder ENV['VAGRANT_SHARED_FOLDER'], "/home/vagrant/shared"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "provision/010_build_corelibs_libdispatch.sh"
  config.vm.provision "shell", path: "provision/020_build_corelibs_foundation.sh"
  config.vm.provision "shell", path: "provision/030_install_libraries.sh", privileged: false
  config.vm.provision "shell", path: "provision/040_build_xctest.sh", privileged: false
  config.vm.provision "shell", path: "provision/050_correct_permissions.sh"
  config.vm.provision "shell", path: "provision/060_collect_libraries.sh", privileged: false
  config.vm.provision "shell", path: "provision/070_clean.sh"
  config.vm.provision "shell", path: "provision/080_setup_devtools.sh", privileged: false

end
