# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"


  if ENV.has_key? 'VAGRANT_SHARED_FOLDER'
    puts "Host folder: #{ENV['VAGRANT_SHARED_FOLDER']} will be mounted to guest: ~/shared"
    config.vm.synced_folder ENV['VAGRANT_SHARED_FOLDER'], "/home/vagrant/shared"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
  end


  config.vm.provision "shell", path: "provision/010_install_dependencies.sh"
  config.vm.provision "shell", path: "provision/020_install_ndk.sh", privileged: false
  config.vm.provision "shell", path: "provision/030_build_libicu.sh", privileged: false
  config.vm.provision "shell", path: "provision/040_clone_swift.sh", privileged: false
  config.vm.provision "shell", path: "provision/050_build_swift.sh", privileged: false
  config.vm.provision "shell", path: "provision/060_install_android_ld.sh"

end
